language: python

python:

  - "3.6"
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev --system

script:
  - pytest --cov=app tests/ --disable-warnings

env:
  - OPENWEATHER_API_URL=http://api.openweathermap.org/data/2.5/forecast LINX_CHALLENGE_TESTING=True

after_success:
  - codecov
