version: '3'

services:
  app:
    container_name: linx_challenge
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"

  postgresql:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=linx
      - POSTGRES_PASSWORD=linx

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
