version: '3'

services:
  postgresql:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=linx
      - POSTGRES_PASSWORD=linx

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
